# Oracle Database Configuration
spring.datasource.url=jdbc:oracle:thin:@//172.16.100.14:1521/orcll
spring.datasource.username=i717824338
spring.datasource.password=i717824338
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Server Port
server.port=8097